### ISSUE TITLE
Feature request: "Nearest Known System" UI should strip commas from input coordinates

### ISSUE THREAD

**Issue by chennin** [spansh/elite-dangerous-issues#3]
It would be helpful if https://spansh.co.uk/nearest stripped commas when sending the API call, to prevent brain farts like I just had

Example, when I tried to find the nearest known system (to the neutron router) to https://spansh.uk/system/1106902095083 , and copied the coords directly from that page, I got the following silly result:

![image](https://user-images.githubusercontent.com/2653277/155847728-fd5b0df0-5644-4f96-bfb4-c200622499e6.png)

Ideally it would automatically do this instead:

![image](https://user-images.githubusercontent.com/2653277/155847744-679780e6-ecda-4b18-88a5-dd2d39eaab1f.png)

**Comment by spansh** [comment]
That is exactly the result I get when I copy and paste the coordinates from a system page into the nearest known system page.  What browser were you using (I was using chrome).

I have made some adjustments to the display of coordinates to make it a little easier to select the individual coordinates and to prevent accidental copying of the comma separator between x, y and z.  Hopefully this makes it easier for you.
