### ISSUE TITLE
make it possible to find a specific type of materials trader with the "station" search tool

### ISSUE THREAD

**Issue by slippycheeze** [spansh/elite-dangerous-issues#7]
I would like to be able to search for a specific type of materials trader, raw, encoded, or manufactured, through the Spansh station search tool; the ability to search along a reference *route* is a wonderful feature not available elsewhere.

It would be nice to be able to do this directly, by having Spansh automatically infer the type from the economy of the system: in the "services" field, being able to select, eg, "encoded material trader" or "material trader (encoded)".

It'd certainly work out just fine, though, if the station "economy" was exposed, letting me configure the right conditions into the search.   I could, eg, easily enough select "refinery" and "extraction" economies along with "material trader" and get the raw material traders.

**Comment by spansh** [comment]
I'll think about doing this, but apparently it's not an exact science.  In the meantime the stations search already has economy available to search

**Comment by spansh** [comment]
This has now been done, you can find new search fields on the station search https://spansh.co.uk/stations
