### ISSUE TITLE
Allow Bodies search to specify a center point

### ISSUE THREAD

**Issue by designerzim** [spansh/elite-dangerous-issues#8]
Using Bodies search always centers on Sol: https://spansh.co.uk/bodies

There should be a field or setting to establish a different center.

Main Fields seems the most likely place for this.

One option would be to add a system selection to the "Distance (LY)" filter in Main Fields.

Or adding an option in Main Fields to specify a center point for the search, that begins with Sol prefilled.

Another option would be to add a new tab, or a top level selection, next to, above, or below the (massive) Search bar.

**Comment by spansh** [comment]
You can try using either "Reference System", "Reference Route", or "Reference Coordinates".  All of those will accomplish the same goal

**Comment by designerzim** [comment]
I was afraid, but also hoping, I was missing something. Thanks!
